// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: services.proto

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Register_Arrival_FullMethodName   = "/main.Register/Arrival"
	Register_Departure_FullMethodName = "/main.Register/Departure"
	Register_Bunkering_FullMethodName = "/main.Register/Bunkering"
)

// RegisterClient is the client API for Register service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RegisterClient interface {
	Arrival(ctx context.Context, in *Ship, opts ...grpc.CallOption) (*Reply, error)
	Departure(ctx context.Context, in *DepartingShip, opts ...grpc.CallOption) (*Reply, error)
	Bunkering(ctx context.Context, in *BunkeringRequest, opts ...grpc.CallOption) (*BunkeringReply, error)
}

type registerClient struct {
	cc grpc.ClientConnInterface
}

func NewRegisterClient(cc grpc.ClientConnInterface) RegisterClient {
	return &registerClient{cc}
}

func (c *registerClient) Arrival(ctx context.Context, in *Ship, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := c.cc.Invoke(ctx, Register_Arrival_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registerClient) Departure(ctx context.Context, in *DepartingShip, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := c.cc.Invoke(ctx, Register_Departure_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registerClient) Bunkering(ctx context.Context, in *BunkeringRequest, opts ...grpc.CallOption) (*BunkeringReply, error) {
	out := new(BunkeringReply)
	err := c.cc.Invoke(ctx, Register_Bunkering_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegisterServer is the server API for Register service.
// All implementations must embed UnimplementedRegisterServer
// for forward compatibility
type RegisterServer interface {
	Arrival(context.Context, *Ship) (*Reply, error)
	Departure(context.Context, *DepartingShip) (*Reply, error)
	Bunkering(context.Context, *BunkeringRequest) (*BunkeringReply, error)
	mustEmbedUnimplementedRegisterServer()
}

// UnimplementedRegisterServer must be embedded to have forward compatible implementations.
type UnimplementedRegisterServer struct {
}

func (UnimplementedRegisterServer) Arrival(context.Context, *Ship) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Arrival not implemented")
}
func (UnimplementedRegisterServer) Departure(context.Context, *DepartingShip) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Departure not implemented")
}
func (UnimplementedRegisterServer) Bunkering(context.Context, *BunkeringRequest) (*BunkeringReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Bunkering not implemented")
}
func (UnimplementedRegisterServer) mustEmbedUnimplementedRegisterServer() {}

// UnsafeRegisterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RegisterServer will
// result in compilation errors.
type UnsafeRegisterServer interface {
	mustEmbedUnimplementedRegisterServer()
}

func RegisterRegisterServer(s grpc.ServiceRegistrar, srv RegisterServer) {
	s.RegisterService(&Register_ServiceDesc, srv)
}

func _Register_Arrival_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Ship)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegisterServer).Arrival(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Register_Arrival_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegisterServer).Arrival(ctx, req.(*Ship))
	}
	return interceptor(ctx, in, info, handler)
}

func _Register_Departure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DepartingShip)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegisterServer).Departure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Register_Departure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegisterServer).Departure(ctx, req.(*DepartingShip))
	}
	return interceptor(ctx, in, info, handler)
}

func _Register_Bunkering_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BunkeringRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegisterServer).Bunkering(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Register_Bunkering_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegisterServer).Bunkering(ctx, req.(*BunkeringRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Register_ServiceDesc is the grpc.ServiceDesc for Register service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Register_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "main.Register",
	HandlerType: (*RegisterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Arrival",
			Handler:    _Register_Arrival_Handler,
		},
		{
			MethodName: "Departure",
			Handler:    _Register_Departure_Handler,
		},
		{
			MethodName: "Bunkering",
			Handler:    _Register_Bunkering_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services.proto",
}
